services:
  inventoryscannercore:
    image: ${DOCKER_REGISTRY-}inventoryscannercore
    container_name: "inventoryscanner-core"
    ports:
    - "5000:8080"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - default
    depends_on:
      - postgres
      - rabbitmq

  postgres:
    image: "postgres:latest"
    container_name: "inventoryscanner-postgres"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
      - "./postgres-init:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=inventoryscanner
    ports:
    - "5432:5432"
    networks:
      - default

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - default
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  rabbitmq-data:

networks:
  default:
