name: Deploy to NAS via docker run script

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.NAS_SSH_PRIVATE_KEY }}

    - name: Configure SSH with Cloudflare Tunnel
      run: |
        mkdir -p ~/.ssh
        echo "Host deploy.gumptiousgoat.com" >> ~/.ssh/config
        echo "  ProxyCommand cloudflared access ssh --hostname %h --id ${{ secrets.CF_ACCESS_CLIENT_ID }} --secret ${{ secrets.CF_ACCESS_CLIENT_SECRET }}" >> ~/.ssh/config
        echo "  User ${{ secrets.NAS_USER }}" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config

    - name: Run remote deploy script
      run: ssh deploy.gumptiousgoat.com "~/deploy-inventoryscanner.sh"